=== mulesoft-labs/anypoint-java-clients/core_services/src/main/resources/schemas/connected-applications/authorization.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "http://cs.anypoint.mulesoft.com/authorization.json",
  "properties": {
    "created_at": {
      "format": "date-time",
      "description": "The time the authorization was created"
    },
    "updated_at": {
      "format": "date-time",
      "description": "The time the authorization was last modified"
    },
    "last_used": {
      "format": "date-time",
      "description": "The time the authorization was last used in an OAuth2 flow"
    },
    "user_id": {
      "type": "string",
      "description": "The ID of the user who granted the authorization"
    },
    "client_id": {
      "type": "string",
      "description": "The ID of the client who is granted the authorization"
    },
    "domain": {
      "type": "string",
      "description": "The domain of the client who is granted the authorization"
    },
    "scopes": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      },
      "minItems": 1
    }
  },
  "required": [
    "created_at",
    "updated_at",
    "user_id",
    "client_id",
    "domain",
    "scopes"
  ],
  "additionalProperties": false
}

=== mulesoft-labs/anypoint-java-clients/core_services/src/main/resources/examples/connected-applications/authorization.json
{
  "created_at": "2018-01-26T22:39:02.312Z",
  "updated_at": "2018-01-26T22:39:02.312Z",
  "last_used": "2018-01-26T22:39:02.312Z",
  "user_id": "b65f412f-7d36-4109-b196-9d5ad07c2083",
  "client_id": "d5e32198-7cc1-4c26-ab83-fd8912e16967",
  "domain": "domain-0",
  "scopes": [
    "read:raml",
    "read:users",
    "offline_access"
  ]
}
