=== mulesoft-labs/anypoint-java-clients/exchange/src/main/resources/schemas/v2/create-contract.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "organizationId": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
    },
    "groupId": {
      "type": "string",
      "maxLength": 256
    },
    "assetId": {
      "type": "string",
      "maxLength": 256
    },
    "version": {
      "type": "string",
      "maxLength": 256
    },
    "versionGroup": {
      "type": "string",
      "maxLength": 256
    },
    "environmentId": {
      "type": "string",
      "maxLength": 256
    },
    "instanceType": {
      "type": "string",
      "enum": ["api", "api-group"]
    },
    "acceptedTerms": {
      "type": "boolean"
    },
    "apiGroupInstanceId": {
      "type": "integer",
      "minimum": 1
    },
    "apiId": {
      "type": "integer",
      "minimum": 1
    },
    "requestedTierId": {
      "type": "integer",
      "minimum": 1
    }
  },
  "additionalProperties": false,
  "allOf": [
    {
      "required": [
        "acceptedTerms",
        "instanceType",
        "organizationId",
        "groupId",
        "assetId",
        "version",
        "versionGroup"
      ]
    },
    {
      "oneOf": [
        {
          "properties": {
            "instanceType": {
              "enum": ["api-group"]
            }
          },
          "required": ["apiGroupInstanceId"]
        },
        {
          "properties": {
            "instanceType": {
              "enum": ["api"]
            }
          },
          "required": ["apiId"]
        }
      ]
    }
  ]
}

=== mulesoft-labs/anypoint-java-clients/exchange/src/main/resources/examples/v2/create-api-group-contract.json
{
  "instanceType": "api-group",
  "acceptedTerms": true,
  "apiGroupInstanceId": 1984,
  "requestedTierId": 7714,
  "organizationId": "0f4a90e6-0da2-41e2-864c-0ec52477dfe5",
  "groupId": "0f4a90e6-0da2-41e2-864c-0ec52477dfe5",
  "assetId": "ministry-of-truth",
  "version": "3.0.0",
  "versionGroup": "v3"
}
